exports.scrapeURLs = [
		{url: "http://lg.ix.kw/alice/routeservers/0/protocols/AS3225_1/routes"},
		{url: 'http://lg.ix.kw/alice/routeservers/0/protocols/AS6412_1/routes'},
		{url: 'http://lg.ix.kw/alice/routeservers/1/protocols/AS6412_1/routes'},
		{url: 'http://lg.ix.kw/alice/routeservers/0/protocols/AS6412_3/routes'},
		{url: 'http://lg.ix.kw/alice/routeservers/1/protocols/AS6412_3/routes'},
		{url: "http://lg.ix.kw/alice/routeservers/0/protocols/AS9155_1/routes"},
		{url: "http://lg.ix.kw/alice/routeservers/1/protocols/AS9155_1/routes"},
		{url: "http://lg.ix.kw/alice/routeservers/0/protocols/AS21050_1/routes"},
		{url: "http://lg.ix.kw/alice/routeservers/1/protocols/AS21050_1/routes"},
		{url: "http://lg.ix.kw/alice/routeservers/0/protocols/AS42961_3/routes"}, 
		{url: "http://lg.ix.kw/alice/routeservers/1/protocols/AS42961_3/routes"},
		{url: "http://lg.ix.kw/alice/routeservers/0/protocols/AS29357_3/routes"}, 
		{url: "http://lg.ix.kw/alice/routeservers/1/protocols/AS29357_3/routes"},
		{url: "http://lg.ix.kw/alice/routeservers/0/protocols/AS47442_1/routes"},
		{url: "http://lg.ix.kw/alice/routeservers/1/protocols/AS47442_1/routes"},	
];